[2023-11-21T17:10:02.356+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: carburants_request.carburants_request scheduled__2023-11-21T16:00:00+00:00 [queued]>
[2023-11-21T17:10:02.361+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: carburants_request.carburants_request scheduled__2023-11-21T16:00:00+00:00 [queued]>
[2023-11-21T17:10:02.362+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-21T17:10:02.378+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): carburants_request> on 2023-11-21 16:00:00+00:00
[2023-11-21T17:10:02.380+0100] {standard_task_runner.py:57} INFO - Started process 55544 to run task
[2023-11-21T17:10:02.383+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'carburants_request', 'carburants_request', 'scheduled__2023-11-21T16:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/carburants_request_DAG.py', '--cfg-path', '/tmp/tmp5mg5xriu']
[2023-11-21T17:10:02.384+0100] {standard_task_runner.py:85} INFO - Job 38: Subtask carburants_request
[2023-11-21T17:10:02.413+0100] {task_command.py:416} INFO - Running <TaskInstance: carburants_request.carburants_request scheduled__2023-11-21T16:00:00+00:00 [running]> on host yzpt-Lenovo-ideapad-320S-14IKB
[2023-11-21T17:10:02.466+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='carburants_request' AIRFLOW_CTX_TASK_ID='carburants_request' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T16:00:00+00:00'
[2023-11-21T17:10:02.792+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yzpt/projects/carburant_gcp/dags/carburants_request.py", line 44, in extract_data
    fields['service'].get('services'),
KeyError: 'service'
[2023-11-21T17:10:02.795+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=carburants_request, task_id=carburants_request, execution_date=20231121T160000, start_date=20231121T161002, end_date=20231121T161002
[2023-11-21T17:10:02.805+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task carburants_request ('service'; 55544)
[2023-11-21T17:10:02.836+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T17:10:02.847+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
