[2023-11-21T17:11:38.897+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: carburants_request.carburants_request scheduled__2023-11-21T16:00:00+00:00 [queued]>
[2023-11-21T17:11:38.904+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: carburants_request.carburants_request scheduled__2023-11-21T16:00:00+00:00 [queued]>
[2023-11-21T17:11:38.904+0100] {taskinstance.py:1361} INFO - Starting attempt 4 of 6
[2023-11-21T17:11:38.920+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): carburants_request> on 2023-11-21 16:00:00+00:00
[2023-11-21T17:11:38.922+0100] {standard_task_runner.py:57} INFO - Started process 55805 to run task
[2023-11-21T17:11:38.928+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'carburants_request', 'carburants_request', 'scheduled__2023-11-21T16:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/carburants_request_DAG.py', '--cfg-path', '/tmp/tmpewuub12x']
[2023-11-21T17:11:38.929+0100] {standard_task_runner.py:85} INFO - Job 41: Subtask carburants_request
[2023-11-21T17:11:38.968+0100] {task_command.py:416} INFO - Running <TaskInstance: carburants_request.carburants_request scheduled__2023-11-21T16:00:00+00:00 [running]> on host yzpt-Lenovo-ideapad-320S-14IKB
[2023-11-21T17:11:39.029+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='carburants_request' AIRFLOW_CTX_TASK_ID='carburants_request' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-21T16:00:00+00:00'
[2023-11-21T17:11:39.351+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yzpt/projects/carburant_gcp/dags/carburants_request.py", line 44, in extract_data
    fields['service'].get('services'),
KeyError: 'service'
[2023-11-21T17:11:39.354+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=carburants_request, task_id=carburants_request, execution_date=20231121T160000, start_date=20231121T161138, end_date=20231121T161139
[2023-11-21T17:11:39.363+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task carburants_request ('service'; 55805)
[2023-11-21T17:11:39.381+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T17:11:39.392+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
