[2023-11-22T23:23:47.976+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xml_parsing.db_insert scheduled__2023-11-22T22:22:00+00:00 [queued]>
[2023-11-22T23:23:47.981+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xml_parsing.db_insert scheduled__2023-11-22T22:22:00+00:00 [queued]>
[2023-11-22T23:23:47.982+0100] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-11-22T23:23:47.995+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): db_insert> on 2023-11-22 22:22:00+00:00
[2023-11-22T23:23:47.997+0100] {standard_task_runner.py:57} INFO - Started process 21954 to run task
[2023-11-22T23:23:48.000+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'xml_parsing', 'db_insert', 'scheduled__2023-11-22T22:22:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/xml_parsing_DAG.py', '--cfg-path', '/tmp/tmplsg5_n2_']
[2023-11-22T23:23:48.001+0100] {standard_task_runner.py:85} INFO - Job 65: Subtask db_insert
[2023-11-22T23:23:48.038+0100] {task_command.py:416} INFO - Running <TaskInstance: xml_parsing.db_insert scheduled__2023-11-22T22:22:00+00:00 [running]> on host yzpt-Lenovo-ideapad-320S-14IKB
[2023-11-22T23:23:48.082+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='xml_parsing' AIRFLOW_CTX_TASK_ID='db_insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T22:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T22:22:00+00:00'
[2023-11-22T23:23:48.082+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: db_insert() missing 1 required positional argument: 'root'
[2023-11-22T23:23:48.087+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=xml_parsing, task_id=db_insert, execution_date=20231122T222200, start_date=20231122T222347, end_date=20231122T222348
[2023-11-22T23:23:48.099+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 65 for task db_insert (db_insert() missing 1 required positional argument: 'root'; 21954)
[2023-11-22T23:23:48.132+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:23:48.143+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
