[2023-11-22T23:23:14.778+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xml_parsing.db_insert scheduled__2023-11-22T22:22:00+00:00 [queued]>
[2023-11-22T23:23:14.785+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xml_parsing.db_insert scheduled__2023-11-22T22:22:00+00:00 [queued]>
[2023-11-22T23:23:14.785+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-22T23:23:14.805+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): db_insert> on 2023-11-22 22:22:00+00:00
[2023-11-22T23:23:14.808+0100] {standard_task_runner.py:57} INFO - Started process 21542 to run task
[2023-11-22T23:23:14.811+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'xml_parsing', 'db_insert', 'scheduled__2023-11-22T22:22:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/xml_parsing_DAG.py', '--cfg-path', '/tmp/tmpvs178sif']
[2023-11-22T23:23:14.812+0100] {standard_task_runner.py:85} INFO - Job 63: Subtask db_insert
[2023-11-22T23:23:14.908+0100] {task_command.py:416} INFO - Running <TaskInstance: xml_parsing.db_insert scheduled__2023-11-22T22:22:00+00:00 [running]> on host yzpt-Lenovo-ideapad-320S-14IKB
[2023-11-22T23:23:14.978+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='xml_parsing' AIRFLOW_CTX_TASK_ID='db_insert' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T22:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-22T22:22:00+00:00'
[2023-11-22T23:23:14.979+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: db_insert() missing 1 required positional argument: 'root'
[2023-11-22T23:23:14.984+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=xml_parsing, task_id=db_insert, execution_date=20231122T222200, start_date=20231122T222314, end_date=20231122T222314
[2023-11-22T23:23:14.996+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 63 for task db_insert (db_insert() missing 1 required positional argument: 'root'; 21542)
[2023-11-22T23:23:15.027+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-22T23:23:15.039+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
