[2023-11-21T17:12:10.671+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: carburants_request.carburants_request manual__2023-11-21T16:12:08.290179+00:00 [queued]>
[2023-11-21T17:12:10.679+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: carburants_request.carburants_request manual__2023-11-21T16:12:08.290179+00:00 [queued]>
[2023-11-21T17:12:10.679+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-21T17:12:10.694+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): carburants_request> on 2023-11-21 16:12:08.290179+00:00
[2023-11-21T17:12:10.696+0100] {standard_task_runner.py:57} INFO - Started process 56149 to run task
[2023-11-21T17:12:10.700+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'carburants_request', 'carburants_request', 'manual__2023-11-21T16:12:08.290179+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/carburants_request_DAG.py', '--cfg-path', '/tmp/tmpny1zpzyw']
[2023-11-21T17:12:10.701+0100] {standard_task_runner.py:85} INFO - Job 42: Subtask carburants_request
[2023-11-21T17:12:10.737+0100] {task_command.py:416} INFO - Running <TaskInstance: carburants_request.carburants_request manual__2023-11-21T16:12:08.290179+00:00 [running]> on host yzpt-Lenovo-ideapad-320S-14IKB
[2023-11-21T17:12:10.798+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='carburants_request' AIRFLOW_CTX_TASK_ID='carburants_request' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T16:12:08.290179+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T16:12:08.290179+00:00'
[2023-11-21T17:12:11.230+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/yzpt/projects/carburant_gcp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yzpt/projects/carburant_gcp/dags/carburants_request.py", line 44, in extract_data
    fields['service'].get('services'),
KeyError: 'service'
[2023-11-21T17:12:11.234+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=carburants_request, task_id=carburants_request, execution_date=20231121T161208, start_date=20231121T161210, end_date=20231121T161211
[2023-11-21T17:12:11.247+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 42 for task carburants_request ('service'; 56149)
[2023-11-21T17:12:11.274+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T17:12:11.286+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
